from __future__ import annotations

import logging
import re
from collections.abc import Callable
from pathlib import Path
from typing import Any

from orca_auto.core.config.files import default_config_path_from_repo_root
from orca_auto.core.paths import is_subpath, validate_job_dir
from orca_auto.core.paths.workflow import workflow_workspace_internal_engine_paths_from_path

from ..config import AppConfig

logger = logging.getLogger(__name__)

RETRY_INP_RE = re.compile(r"\.retry\d+$", re.IGNORECASE)
# Pattern for intermediate inp files auto-generated by ORCA (not user-authored inp files)
ORCA_GENERATED_INP_RE = re.compile(
    r"\.(scfgrad|scfhess|cis|autoci|cipsi|mrci|mdci|eprnmr|loc|nbo|compound|hess)"
    r"(\.retry\d+)?$",
    re.IGNORECASE,
)
CONFIG_ENV_VAR = "ORCA_AUTO_CONFIG"
_MAX_SAMPLE_FILES = 10


def default_config_path() -> str:
    repo_root = Path(__file__).resolve().parents[4]
    return default_config_path_from_repo_root(repo_root, env_var=CONFIG_ENV_VAR)


def _to_resolved_local(path_text: str) -> Path:
    return Path(path_text).expanduser().resolve()


def _workflow_runtime_paths(cfg: AppConfig, path: str | Path) -> dict[str, Path] | None:
    workflow_root = str(getattr(cfg, "workflow_root", "")).strip()
    if not workflow_root:
        return None
    return workflow_workspace_internal_engine_paths_from_path(
        path,
        workflow_root=workflow_root,
        engine="orca",
    )


def _validate_reaction_dir(cfg: AppConfig, reaction_dir_raw: str) -> Path:
    reaction_dir = _to_resolved_local(reaction_dir_raw)
    if not reaction_dir.exists() or not reaction_dir.is_dir():
        raise ValueError(f"Job directory not found: {reaction_dir}")

    runtime_paths = _workflow_runtime_paths(cfg, reaction_dir)
    if runtime_paths is not None:
        return validate_job_dir(
            reaction_dir_raw, str(runtime_paths["allowed_root"]), label="Job directory"
        )

    allowed_root = _to_resolved_local(cfg.runtime.allowed_root)
    if not is_subpath(reaction_dir, allowed_root):
        raise ValueError(
            f"Job directory must be under allowed root: {allowed_root}. got={reaction_dir}"
        )
    return reaction_dir


def _validate_root_scan_dir(cfg: AppConfig, root_raw: str) -> Path:
    root = _to_resolved_local(root_raw)
    if not root.exists() or not root.is_dir():
        raise ValueError(f"Root directory not found: {root}")

    allowed_root = _to_resolved_local(cfg.runtime.allowed_root)
    if root != allowed_root:
        raise ValueError(f"--root must exactly match allowed_root: {allowed_root}. got={root}")
    return root


def _human_bytes(n: int) -> str:
    value = float(n)
    for unit in ("B", "KB", "MB", "GB"):
        if abs(value) < 1024.0:
            return f"{value:.1f} {unit}"
        value /= 1024.0
    return f"{value:.1f} TB"


def finalize_batch_apply(
    summary: dict[str, Any],
    emit_fn: Callable[[dict[str, Any]], None],
    failures: list[dict[str, Any]],
) -> int:
    emit_fn(summary)
    return 1 if failures else 0


def _emit(payload: dict[str, Any]) -> None:
    fields = [
        ("status", "status"),
        ("job_dir", "job_dir"),
        ("reaction_dir", "job_dir"),
        ("selected_inp", "selected_inp"),
        ("attempt_count", "attempt_count"),
        ("reason", "reason"),
        ("run_state", "run_state"),
        ("report_json", "report_json"),
        ("report_md", "report_md"),
    ]
    emitted_labels: set[str] = set()
    for key, label in fields:
        if key not in payload or label in emitted_labels:
            continue
        print(f"{label}: {payload[key]}")
        emitted_labels.add(label)
