"""Slack in ``orca_auto init``: the real command, a scripted terminal and a tmp config.

``input`` and ``getpass`` are replaced by a scripted console; an unscripted
prompt fails the test. The written ``orca_auto.yaml`` is read back through the
real ``load_config`` and ``build_channel``. Nothing is sent: sockets are refused
and no channel's ``send`` is called. Token and channel values are synthetic.

The provider choice is a second yes/no question asked only after Discord is
declined. Accepting Discord keeps its prompts and answers; declining it now
needs one more answer, so an older sequence that ended with that decline does
not keep its meaning.
"""

from __future__ import annotations

import getpass
import socket
import stat
from argparse import Namespace
from collections import deque
from dataclasses import dataclass, field
from pathlib import Path

import pytest
import yaml

from orca_auto.core.messaging import DisabledChannel, build_channel
from orca_auto.core.messaging.discord_bot import DiscordBotChannel
from orca_auto.core.messaging.slack_bot import SlackBotChannel
from orca_auto.orca.commands import init
from orca_auto.orca.config import load_config

# Obviously synthetic values: no real Slack/Discord workspace, token or channel.
_SLACK_TOKEN = "xoxb-synthetic-init-token"
_SLACK_CHANNEL = "C0SYNTHETIC1"
_DISCORD_TOKEN = "synthetic-discord-init-token"
_DISCORD_CHANNEL = "123"

_DISCORD_QUESTION = "Configure Discord notifications now? [y/N]: "
_SLACK_QUESTION = "Configure Slack notifications now? [y/N]: "
_SLACK_TOKEN_PROMPT = "Slack bot token: "
_SLACK_CHANNEL_PROMPT = "Slack default notification channel id: "


@dataclass
class _Console:
    """Scripted answers for the wizard's prompts; an unscripted prompt fails the test."""

    answers: deque[str] = field(default_factory=deque)
    secrets: deque[str] = field(default_factory=deque)
    prompts: list[str] = field(default_factory=list)
    secret_prompts: list[str] = field(default_factory=list)

    def type(self, *answers: str) -> None:
        self.answers.extend(answers)

    def type_secret(self, *answers: str) -> None:
        self.secrets.extend(answers)

    def read(self, prompt: str = "") -> str:
        self.prompts.append(prompt)
        if not self.answers:
            pytest.fail(f"unexpected prompt: {prompt!r}")
        return self.answers.popleft()

    def read_secret(self, prompt: str = "") -> str:
        self.secret_prompts.append(prompt)
        if not self.secrets:
            pytest.fail(f"unexpected secret prompt: {prompt!r}")
        return self.secrets.popleft()


@pytest.fixture
def console(monkeypatch: pytest.MonkeyPatch) -> _Console:
    console = _Console()
    monkeypatch.setattr("builtins.input", console.read)
    monkeypatch.setattr(getpass, "getpass", console.read_secret)
    return console


@pytest.fixture(autouse=True)
def no_network(monkeypatch: pytest.MonkeyPatch) -> None:
    def refuse(*_args: object, **_kwargs: object) -> None:
        raise AssertionError("an init test must not open a network connection")

    monkeypatch.setattr(socket, "create_connection", refuse)
    monkeypatch.setattr(socket.socket, "connect", refuse)


def _run_init(config_path: Path) -> int:
    return init.cmd_init(Namespace(force=True, config=str(config_path)))


def _setup_answers(runs_root: Path, fake_orca: Path) -> tuple[str, ...]:
    """runs root, create it, ORCA executable, max_active_simulations."""

    return (str(runs_root), "y", str(fake_orca), "4")


def _written_messenger(config_path: Path) -> object:
    written = config_path.read_text(encoding="utf-8")
    assert written.startswith("# Generated by orca_auto init\n")
    return yaml.safe_load(written.split("\n", 1)[1])["messenger"]


# --------------------------------------------------------------------------- #
# Interactive Slack configuration prompts
# --------------------------------------------------------------------------- #
def test_init_configures_slack_after_discord_is_declined(
    tmp_path: Path,
    fake_orca: Path,
    console: _Console,
    capsys: pytest.CaptureFixture[str],
) -> None:
    config_path = tmp_path / "config" / "orca_auto.yaml"
    console.type(*_setup_answers(tmp_path / "runs", fake_orca), "n", "y", _SLACK_CHANNEL)
    console.type_secret(_SLACK_TOKEN)

    assert _run_init(config_path) == 0

    # Only the selected provider's section is written.
    assert _written_messenger(config_path) == {
        "provider": "slack",
        "slack": {"bot_token": _SLACK_TOKEN, "default_channel_id": _SLACK_CHANNEL},
    }
    assert console.prompts[4:] == [_DISCORD_QUESTION, _SLACK_QUESTION, _SLACK_CHANNEL_PROMPT]
    assert console.secret_prompts == [_SLACK_TOKEN_PROMPT]
    assert not console.answers
    assert not console.secrets
    output = capsys.readouterr().out
    assert "messenger_provider: slack" in output
    assert _SLACK_TOKEN not in output
    assert stat.S_IMODE(config_path.stat().st_mode) == 0o600

    cfg = load_config(str(config_path))
    channel = build_channel(cfg.messenger)
    assert (cfg.messenger.provider, cfg.messenger.enabled) == ("slack", True)
    assert isinstance(channel, SlackBotChannel)
    assert channel.config.bot_token == _SLACK_TOKEN
    assert channel.config.default_channel_id == _SLACK_CHANNEL


def test_init_slack_prompt_asks_again_until_the_settings_are_complete_and_valid(
    tmp_path: Path,
    fake_orca: Path,
    console: _Console,
    capsys: pytest.CaptureFixture[str],
) -> None:
    config_path = tmp_path / "orca_auto.yaml"
    # An empty token, then a channel name instead of a channel ID, then valid values.
    console.type(
        *_setup_answers(tmp_path / "runs", fake_orca),
        "n",
        "y",
        _SLACK_CHANNEL,
        "general",
        _SLACK_CHANNEL,
    )
    console.type_secret("", _SLACK_TOKEN, _SLACK_TOKEN)

    assert _run_init(config_path) == 0

    assert _written_messenger(config_path) == {
        "provider": "slack",
        "slack": {"bot_token": _SLACK_TOKEN, "default_channel_id": _SLACK_CHANNEL},
    }
    assert console.secret_prompts == [_SLACK_TOKEN_PROMPT] * 3
    assert console.prompts[6:] == [_SLACK_CHANNEL_PROMPT] * 3
    assert not console.answers
    assert not console.secrets
    output = capsys.readouterr().out
    assert "A Slack bot token and a default notification channel id are required." in output
    assert "Invalid Slack notification configuration:" in output
    assert "must be a Slack channel ID." in output
    assert _SLACK_TOKEN not in output


def test_init_declining_both_providers_writes_the_disabled_discord_default(
    tmp_path: Path,
    fake_orca: Path,
    console: _Console,
) -> None:
    config_path = tmp_path / "orca_auto.yaml"
    console.type(*_setup_answers(tmp_path / "runs", fake_orca), "n", "n")

    assert _run_init(config_path) == 0

    # The bytes written today when Discord is declined stay the same.
    assert _written_messenger(config_path) == {
        "provider": "discord",
        "discord": {"bot_token": "", "default_channel_id": ""},
    }
    assert console.prompts[4:] == [_DISCORD_QUESTION, _SLACK_QUESTION]
    assert console.secret_prompts == []
    assert not console.answers

    cfg = load_config(str(config_path))
    assert cfg.messenger.enabled is False
    assert isinstance(build_channel(cfg.messenger), DisabledChannel)


# --------------------------------------------------------------------------- #
# Discord setup and preserved settings controls
# --------------------------------------------------------------------------- #
def test_init_discord_setup_is_unchanged_and_never_asks_about_slack(
    tmp_path: Path,
    fake_orca: Path,
    console: _Console,
) -> None:
    config_path = tmp_path / "orca_auto.yaml"
    console.type(*_setup_answers(tmp_path / "runs", fake_orca), "y", _DISCORD_CHANNEL)
    console.type_secret(_DISCORD_TOKEN)

    assert _run_init(config_path) == 0

    assert _written_messenger(config_path) == {
        "provider": "discord",
        "discord": {"bot_token": _DISCORD_TOKEN, "default_channel_id": _DISCORD_CHANNEL},
    }
    assert _SLACK_QUESTION not in console.prompts
    assert console.secret_prompts == ["Discord bot token: "]
    assert not console.answers

    cfg = load_config(str(config_path))
    assert (cfg.messenger.provider, cfg.messenger.enabled) == ("discord", True)
    assert isinstance(build_channel(cfg.messenger), DiscordBotChannel)


def test_init_keeps_existing_slack_settings_without_asking_for_them(
    tmp_path: Path,
    fake_orca: Path,
    console: _Console,
    capsys: pytest.CaptureFixture[str],
) -> None:
    config_path = tmp_path / "orca_auto.yaml"
    existing = {
        "provider": "slack",
        "slack": {"bot_token": _SLACK_TOKEN, "default_channel_id": _SLACK_CHANNEL},
    }
    config_path.write_text(yaml.safe_dump({"messenger": existing}), encoding="utf-8")
    # The empty answer takes the default: keep the existing messenger settings.
    console.type(*_setup_answers(tmp_path / "runs", fake_orca), "")

    assert _run_init(config_path) == 0

    assert _written_messenger(config_path) == existing
    assert console.prompts[-1] == "Keep the existing messenger settings? [Y/n]: "
    assert _DISCORD_QUESTION not in console.prompts
    assert _SLACK_QUESTION not in console.prompts
    assert console.secret_prompts == []
    output = capsys.readouterr().out
    assert "Preserving existing messenger settings (slack)." in output
    assert "messenger_provider: slack" in output
    assert _SLACK_TOKEN not in output

    cfg = load_config(str(config_path))
    assert isinstance(build_channel(cfg.messenger), SlackBotChannel)
