"""Composable HTML job reports assembled from reusable report components."""

from __future__ import annotations

import html
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..completion_rules import OPT_ROUTE_RE, TS_ROUTE_RE
from ..input_blocks import file_route_lines
from ..scants import first_scan_coordinate_spec, input_uses_scants
from .irc import (
    IrcReportData,
    collect_irc_report_data,
    input_uses_irc,
    irc_report_badges,
    irc_report_component,
    irc_report_meta_html,
)
from .neb import (
    NebReportData,
    collect_neb_report_data,
    input_uses_neb_ts,
    neb_report_badges,
    neb_report_component,
    neb_report_meta_html,
)
from .opt import (
    OptReportData,
    collect_opt_report_data,
    opt_report_badges,
    opt_report_component,
    opt_report_meta_html,
)
from .render import ReportComponent, ReportPage, render_page, verdict_note
from .scants import (
    ScantsReportData,
    collect_scants_report_data,
    scants_report_badges,
    scants_report_component,
    scants_report_meta_html,
)
from .si import structure_kind
from .sp import (
    SpReportData,
    collect_sp_report_data,
    sp_report_badges,
    sp_report_component,
    sp_report_meta_html,
)

# Every flavor shares the fields the composer needs for the page frame
# (title, reason, attempts, last_out_name), so the primary facet is a plain
# union and stays fully type-checked.
JobReportData = NebReportData | ScantsReportData | IrcReportData | OptReportData | SpReportData


@dataclass(frozen=True)
class HtmlReportParts:
    selected_inp: Path
    routes: str
    opt: OptReportData | None = None
    scants: ScantsReportData | None = None
    neb: NebReportData | None = None
    irc: IrcReportData | None = None
    sp: SpReportData | None = None


def compose_job_report_html(reaction_dir: Path, state: Mapping[str, Any]) -> str | None:
    parts = collect_html_report_parts(reaction_dir, state)
    if parts is None:
        return None
    primary = _primary_report_data(parts)
    if primary is None:
        return None

    components = _report_components(parts, primary)
    if not components:
        return None

    badges = _combined_badges(parts, primary)
    sections = tuple(section for component in components for section in component.sections)
    metrics_html = "".join(component.metrics_html for component in components)
    fallback_reason = primary.attempts[-1].analyzer_reason if primary.attempts else ""

    page = ReportPage(
        title=f"{primary.title} · {_kind_label(primary)} report",
        badges=badges,
        meta_html=_meta_html(primary),
        verdict_html=verdict_note(primary.reason, fallback_reason),
        metrics_html=metrics_html,
        sections=sections,
        footer_html=(
            "Generated by orca_auto &#183; last output: "
            f"<code>{html.escape(primary.last_out_name)}</code>"
        ),
    )
    return render_page(page)


def collect_html_report_parts(
    reaction_dir: Path,
    state: Mapping[str, Any],
) -> HtmlReportParts | None:
    selected_raw = str(state.get("selected_inp") or "").strip()
    if not selected_raw:
        return None
    selected_inp = Path(selected_raw)
    route_lines = file_route_lines(selected_inp)
    routes = " ".join(route_lines)

    has_irc = input_uses_irc(selected_inp)
    has_scants = input_uses_scants(selected_inp)
    has_neb_ts = input_uses_neb_ts(selected_inp)
    has_relaxed_scan = first_scan_coordinate_spec(selected_inp) is not None
    has_ts = bool(TS_ROUTE_RE.search(routes))
    has_opt = bool(OPT_ROUTE_RE.search(routes))

    neb = collect_neb_report_data(reaction_dir, state) if has_neb_ts else None
    scants: ScantsReportData | None = None
    if has_scants:
        scants = collect_scants_report_data(reaction_dir, state)
    elif has_opt and has_relaxed_scan:
        scants = collect_scants_report_data(reaction_dir, state, kind="scan")

    opt: OptReportData | None = None
    if (has_ts or has_opt) and neb is None and scants is None:
        opt = collect_opt_report_data(
            reaction_dir,
            state,
            kind="ts" if has_ts else "opt",
        )

    irc = collect_irc_report_data(reaction_dir, state) if has_irc else None

    sp: SpReportData | None = None
    if all(part is None for part in (opt, scants, neb, irc)):
        if structure_kind(selected_inp) != "sp":
            return None
        sp = collect_sp_report_data(reaction_dir, state)

    if all(part is None for part in (opt, scants, neb, irc, sp)):
        return None
    return HtmlReportParts(
        selected_inp=selected_inp,
        routes=routes,
        opt=opt,
        scants=scants,
        neb=neb,
        irc=irc,
        sp=sp,
    )


def _report_components(
    parts: HtmlReportParts,
    primary: JobReportData,
) -> tuple[ReportComponent, ...]:
    components: list[ReportComponent] = []

    if parts.neb is not None:
        components.append(
            neb_report_component(
                parts.neb,
                include_attempt_metric=primary is parts.neb,
                include_attempt_chain=primary is parts.neb,
                include_frequency_metric=parts.irc is None,
                include_vibrational=parts.irc is None,
            )
        )
    if parts.scants is not None:
        components.append(
            scants_report_component(
                parts.scants,
                include_attempt_metric=primary is parts.scants,
                include_attempt_chain=primary is parts.scants,
                include_frequency_metric=parts.irc is None,
                include_vibrational=parts.irc is None,
            )
        )
    if parts.opt is not None:
        components.append(
            opt_report_component(
                parts.opt,
                include_attempt_metric=primary is parts.opt,
                include_attempt_chain=primary is parts.opt,
                include_energy_metric=parts.irc is None,
                include_frequency_metric=parts.irc is None,
                include_vibrational=parts.irc is None,
            )
        )
    if parts.irc is not None:
        components.append(
            irc_report_component(
                parts.irc,
                include_attempt_metric=primary is parts.irc,
                include_attempt_chain=primary is parts.irc,
                include_common_metric=primary is parts.irc,
                include_optimization=(
                    parts.opt is None and parts.neb is None and parts.scants is None
                ),
            )
        )
    if parts.sp is not None:
        components.append(sp_report_component(parts.sp))

    return tuple(component for component in components if component.sections)


def _primary_report_data(parts: HtmlReportParts) -> JobReportData | None:
    # The primary facet supplies the page title, status, footer, and the one
    # attempt chain. Other detected calculation facets contribute sections.
    return parts.neb or parts.scants or parts.irc or parts.opt or parts.sp


def _kind_label(primary: JobReportData) -> str:
    if isinstance(primary, NebReportData):
        return "NEB-TS"
    if isinstance(primary, ScantsReportData):
        return primary.kind_label()
    if isinstance(primary, IrcReportData):
        return "IRC"
    if isinstance(primary, OptReportData):
        return primary.kind_label()
    return "SP"


def _combined_badges(
    parts: HtmlReportParts,
    primary: JobReportData,
) -> tuple[tuple[str, str], ...]:
    if isinstance(primary, NebReportData):
        badges = list(neb_report_badges(primary))
    elif isinstance(primary, ScantsReportData):
        badges = list(scants_report_badges(primary))
    elif isinstance(primary, IrcReportData):
        badges = list(irc_report_badges(primary))
    elif isinstance(primary, OptReportData):
        badges = list(opt_report_badges(primary))
    else:
        badges = list(sp_report_badges(primary))

    for extra in (
        neb_report_badges(parts.neb) if parts.neb is not None and parts.neb is not primary else (),
        irc_report_badges(parts.irc) if parts.irc is not None and parts.irc is not primary else (),
    ):
        _extend_unique_badges(badges, extra)
    return tuple(badges)


def _extend_unique_badges(
    badges: list[tuple[str, str]],
    extra: Sequence[tuple[str, str]],
) -> None:
    seen = {badge for badge in badges}
    for badge in extra:
        if badge in seen:
            continue
        badges.append(badge)
        seen.add(badge)


def _meta_html(primary: JobReportData) -> str:
    if isinstance(primary, NebReportData):
        return neb_report_meta_html(primary)
    if isinstance(primary, ScantsReportData):
        return scants_report_meta_html(primary)
    if isinstance(primary, IrcReportData):
        return irc_report_meta_html(primary)
    if isinstance(primary, OptReportData):
        return opt_report_meta_html(primary)
    return sp_report_meta_html(primary)


__all__ = [
    "HtmlReportParts",
    "JobReportData",
    "collect_html_report_parts",
    "compose_job_report_html",
]
