"""Composable HTML job reports assembled from reusable report components."""

from __future__ import annotations

import html
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..completion_rules import RouteFacts, route_facts
from ..evidence import final_out_name, structure_kind
from .attempts import attempt_dicts, duration_text
from .irc import IrcReportData, collect_irc_report_data, irc_report_component
from .neb import NebReportData, collect_neb_report_data, neb_report_component
from .opt import OptReportData, collect_opt_report_data, opt_report_component
from .render import ReportComponent, ReportHeader, ReportPage, render_page, verdict_note
from .scan import ScanReportData, collect_scan_report_data, scan_report_component
from .sp import SpReportData, collect_sp_report_data, sp_report_component

JobReportData = NebReportData | ScanReportData | IrcReportData | OptReportData | SpReportData


@dataclass(frozen=True)
class HtmlReportParts:
    header: ReportHeader
    opt: OptReportData | None = None
    scan: ScanReportData | None = None
    neb: NebReportData | None = None
    irc: IrcReportData | None = None
    sp: SpReportData | None = None


def compose_job_report_html(reaction_dir: Path, state: Mapping[str, Any]) -> str | None:
    parts = collect_html_report_parts(reaction_dir, state)
    if parts is None:
        return None
    primary, components = _report_components(parts)
    # The other facets repeat the status badges and add only their own.
    badges = list(primary.badges)
    for component in components:
        for badge in component.badges:
            if badge not in badges:
                badges.append(badge)

    header = parts.header
    page = ReportPage(
        title=f"{header.title} · {primary.kind_label} report",
        badges=tuple(badges),
        meta_html=primary.meta_html,
        verdict_html=verdict_note(header.reason, header.last_analyzer_reason),
        metrics_html="".join(component.metrics_html for component in components),
        sections=tuple(section for component in components for section in component.sections),
        footer_html="Generated by orca_auto" + _last_output_footer_html(header.last_out_name),
    )
    return render_page(page)


def _last_output_footer_html(last_out_name: str) -> str:
    # ``last_out_name`` follows ``evidence.final_out_name``: empty when the
    # recorded final output is gone, in which case the footer names nothing
    # rather than an earlier attempt's file.
    if not last_out_name:
        return ""
    return f" &#183; last output: <code>{html.escape(last_out_name)}</code>"


def collect_html_report_parts(
    reaction_dir: Path,
    state: Mapping[str, Any],
) -> HtmlReportParts | None:
    selected_raw = str(state.get("selected_inp") or "").strip()
    if not selected_raw:
        return None
    route = route_facts(Path(selected_raw))
    header = _report_header(reaction_dir, state, route)

    neb = collect_neb_report_data(state, header) if route.is_neb_ts else None
    scan = collect_scan_report_data(state, route, header) if route.is_relaxed_scan else None
    opt: OptReportData | None = None
    if (route.is_ts or route.is_opt) and neb is None and scan is None:
        opt = collect_opt_report_data(state, route, header)
    irc = collect_irc_report_data(state, route, header) if route.is_irc else None

    sp: SpReportData | None = None
    if all(part is None for part in (opt, scan, neb, irc)):
        if structure_kind(route) != "sp":
            return None
        sp = collect_sp_report_data(reaction_dir, state, route, header)

    return HtmlReportParts(header=header, opt=opt, scan=scan, neb=neb, irc=irc, sp=sp)


def _report_header(reaction_dir: Path, state: Mapping[str, Any], route: RouteFacts) -> ReportHeader:
    final_result = state.get("final_result")
    final_payload: Mapping[str, Any] = final_result if isinstance(final_result, Mapping) else {}
    attempts = attempt_dicts(state)
    return ReportHeader(
        title=reaction_dir.name or str(reaction_dir),
        job_id=str(state.get("job_id") or ""),
        status=str(state.get("status") or ""),
        reason=str(final_payload.get("reason") or ""),
        route_lines=route.route_lines,
        started_at=str(state.get("started_at") or ""),
        finished_at=str(final_payload.get("completed_at") or ""),
        total_duration_text=duration_text(
            state.get("started_at"), final_payload.get("completed_at")
        ),
        last_analyzer_reason=str(attempts[-1].get("analyzer_reason") or "") if attempts else "",
        last_out_name=final_out_name(state),
    )


def _report_components(
    parts: HtmlReportParts,
) -> tuple[ReportComponent, tuple[ReportComponent, ...]]:
    """The primary facet's component and every component in page order.

    The primary facet (NEB-TS, relaxed scan, IRC, Opt, then SP) names the page,
    leads its badges and meta line, and alone carries the attempt chain.
    """
    primary = parts.neb or parts.scan or parts.irc or parts.opt or parts.sp
    irc_present = parts.irc is not None
    facets: list[tuple[JobReportData, ReportComponent]] = []
    if parts.neb is not None:
        component = neb_report_component(
            parts.neb, is_primary=parts.neb is primary, irc_present=irc_present
        )
        facets.append((parts.neb, component))
    if parts.scan is not None:
        component = scan_report_component(
            parts.scan, is_primary=parts.scan is primary, irc_present=irc_present
        )
        facets.append((parts.scan, component))
    if parts.opt is not None:
        component = opt_report_component(
            parts.opt, is_primary=parts.opt is primary, irc_present=irc_present
        )
        facets.append((parts.opt, component))
    if parts.irc is not None:
        component = irc_report_component(
            parts.irc,
            is_primary=parts.irc is primary,
            optimization_elsewhere=any(
                part is not None for part in (parts.neb, parts.scan, parts.opt)
            ),
        )
        facets.append((parts.irc, component))
    if parts.sp is not None:
        facets.append((parts.sp, sp_report_component(parts.sp)))
    primary_component = next(component for data, component in facets if data is primary)
    return primary_component, tuple(component for _data, component in facets)


__all__ = [
    "HtmlReportParts",
    "JobReportData",
    "collect_html_report_parts",
    "compose_job_report_html",
]
